from typing import Any

import matplotlib.pyplot as plt
from matplotlib.axes import Axes
import pandas as pd
import seaborn as sns


def violinstrip(
    data: pd.DataFrame,
    x: Any = None,
    y: Any = None,
    hue: Any = None,
    *,
    inner: Any = None,
    cut: int | float = 0,
    alpha: int | float = 0.5,
    s: int | float = 1,
    jitter: int | float | bool = 0.4,
    zorder: int = 0,
    ax: Axes | None = None,
    violin_kws: dict[str, Any] | None = None,
    strip_kws: dict[str, Any] | None = None,
) -> Axes:
    """
    Overlay a strip plot on a violin plot to visualize distributions and raw points.

    This function combines `seaborn.violinplot`, which visualizes the estimated
    data distribution, with `seaborn.stripplot`, which displays individual
    observations. This allows the distribution shape and the underlying raw
    data points to be inspected simultaneously.

    Parameters
    ----------
    data : pd.DataFrame
        Input data structure.
    x, y : str, optional
        Variables that specify positions on the x and y axes.
    hue : str, optional
        Grouping variable that produces elements with different colors.
    inner : str or None, optional
        Representation of the datapoints in the violin interior.
        Defaults to None to avoid redundancy with the overlaid strip plot.
    cut : int or float, default 0
        Distance to extend the violin density past the extreme datapoints.
        A value of 0 limits the violin range to the observed data range.
    alpha : int or float, default 0.5
        Opacity of the violin plot.
    s : int or float, default 1
        Size of the markers in the strip plot.
    jitter : int, float, or bool, default 0.4
        Amount of jitter applied along the categorical axis to the strip plot
        points. If True, the amount of jitter is determined automatically.
    zorder : int, default 0
        Drawing order of the strip plot points. Higher values place the points
        above elements with lower z-order values.
    ax : matplotlib.axes.Axes, optional
        Pre-existing Axes on which to draw the plot. If None, a new figure and
        Axes are created.
    violin_kws : dict, optional
        Additional keyword arguments passed only to `seaborn.violinplot`.
    strip_kws : dict, optional
        Additional keyword arguments passed only to `seaborn.stripplot`.
        By default, the strip plot legend is disabled to avoid duplicated
        legend entries when `hue` is specified.

    Returns
    -------
    matplotlib.axes.Axes
        The Axes object containing the violin and strip plots.

    Notes
    -----
    When `hue` is specified, both plot layers use the same grouping variable.
    The legend is generated by the violin plot, while the strip plot legend is
    disabled by default to prevent duplicated entries.
    """
    if ax is None:
        _, ax = plt.subplots()

    violin_kws = {} if violin_kws is None else dict(violin_kws)
    strip_kws = {} if strip_kws is None else dict(strip_kws)

    strip_kws.setdefault("legend", False)

    sns.violinplot(
        data=data,
        x=x,
        y=y,
        hue=hue,
        inner=inner,
        cut=cut,
        alpha=alpha,
        ax=ax,
        **violin_kws,
    )

    sns.stripplot(
        data=data,
        x=x,
        y=y,
        hue=hue,
        s=s,
        jitter=jitter,
        zorder=zorder,
        ax=ax,
        **strip_kws,
    )

    return ax
